"""Typed result models shared across AgroManch services.

These are plain dataclasses (no third-party schema library) so they can be
serialized straight to JSON for the future AgroManch API layer.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any

# Which bundle items feed which publishing platforms (one-click handoff).
PLATFORM_MAP: dict[str, list[str]] = {
    "instagram": [
        "instagram_carousel",
        "carousel_image_prompts",
        "story_prompt",
        "hook",
        "cta",
        "reel_video_prompts",
        "veo_video_prompt",
        "voiceover_script",
        "subtitle_srt",
    ],
    "facebook": ["facebook_post", "image_prompt", "hook", "cta"],
    "youtube_shorts": [
        "youtube_shorts_script",
        "veo_video_prompt",
        "voiceover_script",
        "subtitle_srt",
        "thumbnail_prompt",
        "seo_keywords",
        "hook",
        "cta",
    ],
    "whatsapp": ["whatsapp_broadcast", "cta"],
    "telegram": ["whatsapp_broadcast", "blog", "cta"],
}


@dataclass(slots=True)
class SourceRef:
    """A citation back to a NotebookLM source document."""

    source_id: str
    citation_number: int | None = None
    title: str | None = None
    cited_text: str | None = None

    def label(self) -> str:
        num = f"[{self.citation_number}] " if self.citation_number else ""
        return f"{num}{self.title or self.source_id}"

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class CitedAnswer:
    """A verified answer grounded in the agricultural knowledge base."""

    question: str
    answer: str
    references: list[SourceRef] = field(default_factory=list)
    conversation_id: str | None = None
    language: str = "en"

    def to_markdown(self) -> str:
        lines = [f"### Q: {self.question}", "", self.answer]
        if self.references:
            lines += ["", "**Sources:**"]
            lines += [f"- {ref.label()}" for ref in self.references]
        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class VerifiedContext:
    """Trusted agricultural context retrieved from NotebookLM for a topic.

    This is the *only* thing NotebookLM produces in the current architecture:
    grounded facts plus citations that Gemini then turns into content or advice.
    """

    topic: str
    context_text: str
    references: list[SourceRef] = field(default_factory=list)
    grounded: bool = True

    @property
    def is_empty(self) -> bool:
        return not self.context_text.strip()

    def to_prompt_block(self) -> str:
        """Render the context for injection into a Gemini prompt."""
        if self.is_empty:
            return "VERIFIED CONTEXT: (none available)"
        lines = ["VERIFIED CONTEXT (from trusted agricultural documents):", "", self.context_text]
        if self.references:
            lines += ["", "SOURCES:"]
            lines += [f"- {ref.label()}" for ref in self.references]
        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class GeneratedContent:
    """A piece of farmer-facing content generated by Gemini from verified context."""

    kind: str  # e.g. "instagram_carousel", "whatsapp_broadcast"
    topic: str
    body: str
    language: str = "en"
    references: list[SourceRef] = field(default_factory=list)
    grounded: bool = True

    def to_markdown(self) -> str:
        lines = [f"## {self.kind.replace('_', ' ').title()}: {self.topic}", "", self.body]
        if not self.grounded:
            lines.insert(1, "> ⚠️ UNVERIFIED — generated without trusted-source grounding.")
        if self.references:
            lines += ["", "---", "**Knowledge sources:**"]
            lines += [f"- {ref.label()}" for ref in self.references]
        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class ContentBundle:
    """The full multi-asset output of one content request, ready to publish.

    ``items`` maps each bundle kind (research_summary, instagram_carousel, …) to
    its generated content. All items share one ``VerifiedContext`` so the whole
    bundle is consistent and grounded in the same sources.
    """

    topic: str
    context: VerifiedContext
    items: dict[str, GeneratedContent] = field(default_factory=dict)
    language: str = "en"
    angle: str | None = None  # marketing angle used for the whole package
    # Optional internal artifacts (additive; populated by the review layer).
    review_report: str | None = None
    learning_snapshot: dict[str, Any] | None = None
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def get(self, kind: str) -> GeneratedContent | None:
        return self.items.get(kind)

    def publishing_map(self) -> dict[str, list[str]]:
        """Platform -> the bundle items it publishes (only items present)."""
        return {
            platform: [k for k in kinds if k in self.items]
            for platform, kinds in PLATFORM_MAP.items()
        }

    def manifest(self) -> dict[str, Any]:
        """JSON-serializable handoff for a one-click publishing worker."""
        return {
            "topic": self.topic,
            "language": self.language,
            "angle": self.angle,
            "created_at": self.created_at,
            "grounded": self.context.grounded and not self.context.is_empty,
            "sources": [ref.to_dict() for ref in self.context.references],
            "items": {kind: content.to_dict() for kind, content in self.items.items()},
            "publishing": self.publishing_map(),
        }


@dataclass(slots=True)
class DoseRecommendation:
    """Offline pesticide/fertilizer dose calculation for one field.

    Values mirror what an Indian product label states: a dose per hectare and
    a recommended spray volume. The calculator converts those to the farmer's
    actual field size and knapsack tank.
    """

    product: str
    crop: str
    dose_per_ha: float  # ml or g of product per hectare (from the label)
    unit: str  # "ml" or "g"
    area_ha: float
    spray_volume_per_ha: float  # litres of water per hectare
    tank_capacity_l: float  # knapsack/sprayer tank size in litres

    @property
    def total_product(self) -> float:
        """Total product needed for the field, in ``unit``."""
        return round(self.dose_per_ha * self.area_ha, 2)

    @property
    def total_water_l(self) -> float:
        return round(self.spray_volume_per_ha * self.area_ha, 2)

    @property
    def tanks_needed(self) -> float:
        return round(self.total_water_l / self.tank_capacity_l, 2)

    @property
    def product_per_tank(self) -> float:
        """Product to add to each full tank, in ``unit``."""
        return round(
            self.dose_per_ha / self.spray_volume_per_ha * self.tank_capacity_l, 2
        )

    def to_markdown(self) -> str:
        return "\n".join(
            [
                f"### Dose plan: {self.product} on {self.crop}",
                "",
                f"- Field size: {self.area_ha} ha",
                f"- Label dose: {self.dose_per_ha} {self.unit}/ha "
                f"in {self.spray_volume_per_ha} L water/ha",
                f"- Total product needed: **{self.total_product} {self.unit}**",
                f"- Total spray water: **{self.total_water_l} L** "
                f"(~{self.tanks_needed} tanks of {self.tank_capacity_l} L)",
                f"- Add **{self.product_per_tank} {self.unit} per tank**",
                "",
                "> Always follow the registered label, wear protective equipment,"
                " observe pre-harvest intervals, and confirm with your local"
                " KVK/agriculture officer.",
            ]
        )

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data.update(
            total_product=self.total_product,
            total_water_l=self.total_water_l,
            tanks_needed=self.tanks_needed,
            product_per_tank=self.product_per_tank,
        )
        return data
