"""Content generation — a thin wrapper over the unified generator.

Content is generated by Gemini from NotebookLM-verified context. This service
just exposes channel-level helpers; the AI path lives in
:class:`~agromanch_ai.ai.generator.AgroManchGenerator`.
"""

from __future__ import annotations

from pathlib import Path

from agromanch_ai.ai.generator import AgroManchGenerator
from agromanch_ai.config import Settings
from agromanch_ai.logging import get_logger
from agromanch_ai.models import GeneratedContent, VerifiedContext
from agromanch_ai.prompts.content_prompts import CONTENT_SPECS
from agromanch_ai.utils.text import safe_filename

logger = get_logger("content")


class ContentService:
    """Generate single content assets (carousels, posts, scripts, prompts…)."""

    def __init__(self, generator: AgroManchGenerator, settings: Settings) -> None:
        self._generator = generator
        self._settings = settings

    @staticmethod
    def kinds() -> list[str]:
        return sorted(CONTENT_SPECS)

    async def generate(
        self,
        notebook_id: str,
        kind: str,
        topic: str,
        *,
        context: VerifiedContext | None = None,
        require_grounding: bool | None = None,
    ) -> GeneratedContent:
        if kind not in CONTENT_SPECS:
            raise KeyError(f"Unknown content kind {kind!r}. Available: {self.kinds()}")
        return await self._generator.run(
            kind,
            topic=topic,
            notebook_id=notebook_id,
            context=context,
            require_grounding=require_grounding,
        )

    def save(self, content: GeneratedContent) -> Path:
        out_dir = self._settings.ensure_output_dir()
        path = out_dir / f"{safe_filename(content.topic)}__{content.kind}.md"
        path.write_text(content.to_markdown() + "\n", encoding="utf-8")
        logger.info("Saved %s -> %s", content.kind, path)
        return path
